use_frameworks!

platform :ios, '9.0'

target 'SEPhotoAlbum_Example' do
  pod 'SEPhotoAlbum', :path => '../'

end

# Swift 版本声明
post_install do |installer|
    installer.pods_project.targets.each do |target|
        
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '5.0'
                config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'        
        end
    end
end
